better build script

diff --git a/bin/buildAll b/bin/buildAll
--- a/bin/buildAll
+++ b/bin/buildAll
@@ -1,15 +1,25 @@
 #! /bin/bash
 
-TUNE_FLAGS="-march=native -mcpu=native -mtune=native"
+TUNE_FLAGS="-march=native -mtune=native"
 
 echo -en "\n"
-echo -en "Starting CppSpikes build script with:\n"
+echo -en "Starting 'CppSpikes' build script with:\n"
 echo -en "  TUNE_FLAGS=${TUNE_FLAGS}\n"
 echo -en "\n\n"
 
-m="AtomicExchangeSpikes"
-echo -en "--> Building '$m'...";
-g++ -O0 ${TUNE_FLAGS} -pthread "../${m}.cpp" -o "./${m}" && echo " OK" || echo " FAILED"
+
+function build() {
+	spikeName="$1"
+	O_FLAG="$2"
+	echo -en "--> Building '$spikeName' with '$O_FLAG'..";
+	for compiler in g++ clang++; do
+		echo -en ". ${compiler}"
+		${compiler} ${O_FLAG} ${TUNE_FLAGS} -pthread "../${spikeName}.cpp" -o "./${spikeName}_${compiler}" && echo -en " OK" || echo -en " FAILED"
+	done
+	echo "."
+}
+
+build "AtomicExchangeSpikes" "-O3"
 
 echo -en "\nDone.\n\n"
 ls -lrt
